<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR1HkJ0F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR1HkJ0F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR1HkJ0F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR1HkJ0F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR1HkJ0F\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R1HkJ0F',
    'container.build_id' => 'e87cb37b',
    'container.build_time' => 1609248884,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR1HkJ0F');
